CREATE DATABASE IF NOT EXISTS HACKATHON;
USE HACKATHON;
CREATE TABLE IF NOT EXISTS USER(
    id INT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(50),
    email VARCHAR(30),
    password VARCHAR(100),
    phone_no VARCHAR(10),
    created_time DATE DEFAULT SYSDATE()
);
CREATE TABLE BLOGS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(20),
    contents VARCHAR(30),
    created_time DATE DEFAULT SYSDATE(),
    user_id INT NOT NULL,
    category_id INT NOT NULL,
    FOREIGN KEY(user_id) REFERENCES USER(id),
    FOREIGN KEY(category_id) REFERENCES CATEGORIES(id),
);
CREATE TABLE CATEGORIES(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30),
    description VARCHAR(50)
)